GET http://localhost:3000/

###

GET http://localhost:3000/api/products/

###

PUT http://localhost:3000/api/products/2
Content-type: application/json

{
    "name": "Hörnsoffa",
    "description": "En bra hörnsoffa",
    "price": "12999"
}

###

DELETE http://localhost:3000/api/products/1

###

POST http://localhost:3000/api/products/
Content-type: application/json

{
    "name": "Matta",
    "description": "En fin matta",
    "price": "2499"
}